// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notification

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, userID uuid.UUID) ([]Notification, int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []Notification
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]Notification, int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []Notification); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) int64); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) List(ctx any, userID any) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(notifications []Notification, n int64, err error) *MockService_List_Call {
	_c.Call.Return(notifications, n, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]Notification, int64, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function for the type MockService
func (_mock *MockService) MarkAllRead(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockService_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) MarkAllRead(ctx any, userID any) *MockService_MarkAllRead_Call {
	return &MockService_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID)}
}

func (_c *MockService_MarkAllRead_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_MarkAllRead_Call) Return(err error) *MockService_MarkAllRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_MarkAllRead_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockService_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function for the type MockService
func (_mock *MockService) MarkRead(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockService_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) MarkRead(ctx any, userID any, id any) *MockService_MarkRead_Call {
	return &MockService_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, userID, id)}
}

func (_c *MockService_MarkRead_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_MarkRead_Call) Return(err error) *MockService_MarkRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_MarkRead_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockService_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountUnread provides a mock function for the type MockRepository
func (_mock *MockRepository) CountUnread(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUnread")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CountUnread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUnread'
type MockRepository_CountUnread_Call struct {
	*mock.Call
}

// CountUnread is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) CountUnread(ctx any, userID any) *MockRepository_CountUnread_Call {
	return &MockRepository_CountUnread_Call{Call: _e.mock.On("CountUnread", ctx, userID)}
}

func (_c *MockRepository_CountUnread_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRepository_CountUnread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CountUnread_Call) Return(n int64, err error) *MockRepository_CountUnread_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CountUnread_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int64, error)) *MockRepository_CountUnread_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockRepository
func (_mock *MockRepository) ListByUser(ctx context.Context, userID uuid.UUID, limit int) ([]Notification, error) {
	ret := _mock.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]Notification, error)); ok {
		return returnFunc(ctx, userID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []Notification); ok {
		r0 = returnFunc(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
func (_e *MockRepository_Expecter) ListByUser(ctx any, userID any, limit any) *MockRepository_ListByUser_Call {
	return &MockRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, limit)}
}

func (_c *MockRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int)) *MockRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ListByUser_Call) Return(notifications []Notification, err error) *MockRepository_ListByUser_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *MockRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int) ([]Notification, error)) *MockRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkAllRead(ctx context.Context, userID uuid.UUID, now time.Time) error {
	ret := _mock.Called(ctx, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockRepository_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - now time.Time
func (_e *MockRepository_Expecter) MarkAllRead(ctx any, userID any, now any) *MockRepository_MarkAllRead_Call {
	return &MockRepository_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID, now)}
}

func (_c *MockRepository_MarkAllRead_Call) Run(run func(ctx context.Context, userID uuid.UUID, now time.Time)) *MockRepository_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkAllRead_Call) Return(err error) *MockRepository_MarkAllRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkAllRead_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, now time.Time) error) *MockRepository_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkRead(ctx context.Context, userID uuid.UUID, id uuid.UUID, now time.Time) (bool, error) {
	ret := _mock.Called(ctx, userID, id, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) (bool, error)); ok {
		return returnFunc(ctx, userID, id, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) bool); ok {
		r0 = returnFunc(ctx, userID, id, now)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, id, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockRepository_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - now time.Time
func (_e *MockRepository_Expecter) MarkRead(ctx any, userID any, id any, now any) *MockRepository_MarkRead_Call {
	return &MockRepository_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, userID, id, now)}
}

func (_c *MockRepository_MarkRead_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, now time.Time)) *MockRepository_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_MarkRead_Call) Return(b bool, err error) *MockRepository_MarkRead_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_MarkRead_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, now time.Time) (bool, error)) *MockRepository_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}
