// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package booking

import (
	"context"
	"jongyoung/internal/notification"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Board provides a mock function for the type MockService
func (_mock *MockService) Board(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, date time.Time) (Board, error) {
	ret := _mock.Called(ctx, userID, restaurantID, date)

	if len(ret) == 0 {
		panic("no return value specified for Board")
	}

	var r0 Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) (Board, error)); ok {
		return returnFunc(ctx, userID, restaurantID, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) Board); ok {
		r0 = returnFunc(ctx, userID, restaurantID, date)
	} else {
		r0 = ret.Get(0).(Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, restaurantID, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Board_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Board'
type MockService_Board_Call struct {
	*mock.Call
}

// Board is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - restaurantID uuid.UUID
//   - date time.Time
func (_e *MockService_Expecter) Board(ctx any, userID any, restaurantID any, date any) *MockService_Board_Call {
	return &MockService_Board_Call{Call: _e.mock.On("Board", ctx, userID, restaurantID, date)}
}

func (_c *MockService_Board_Call) Run(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, date time.Time)) *MockService_Board_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Board_Call) Return(board Board, err error) *MockService_Board_Call {
	_c.Call.Return(board, err)
	return _c
}

func (_c *MockService_Board_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, date time.Time) (Board, error)) *MockService_Board_Call {
	_c.Call.Return(run)
	return _c
}

// Cancel provides a mock function for the type MockService
func (_mock *MockService) Cancel(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, bookingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - bookingID uuid.UUID
func (_e *MockService_Expecter) Cancel(ctx any, userID any, bookingID any) *MockService_Cancel_Call {
	return &MockService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, userID, bookingID)}
}

func (_c *MockService_Cancel_Call) Run(run func(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID)) *MockService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Cancel_Call) Return(err error) *MockService_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Cancel_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID) error) *MockService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, c Choice) (Booking, error) {
	ret := _mock.Called(ctx, userID, restaurantID, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, Choice) (Booking, error)); ok {
		return returnFunc(ctx, userID, restaurantID, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, Choice) Booking); ok {
		r0 = returnFunc(ctx, userID, restaurantID, c)
	} else {
		r0 = ret.Get(0).(Booking)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, Choice) error); ok {
		r1 = returnFunc(ctx, userID, restaurantID, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - restaurantID uuid.UUID
//   - c Choice
func (_e *MockService_Expecter) Create(ctx any, userID any, restaurantID any, c any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, userID, restaurantID, c)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, c Choice)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 Choice
		if args[3] != nil {
			arg3 = args[3].(Choice)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(booking Booking, err error) *MockService_Create_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, c Choice) (Booking, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID) (View, error) {
	ret := _mock.Called(ctx, userID, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 View
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (View, error)); ok {
		return returnFunc(ctx, userID, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) View); ok {
		r0 = returnFunc(ctx, userID, bookingID)
	} else {
		r0 = ret.Get(0).(View)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - bookingID uuid.UUID
func (_e *MockService_Expecter) Get(ctx any, userID any, bookingID any) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, userID, bookingID)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(view View, err error) *MockService_Get_Call {
	_c.Call.Return(view, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID) (View, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListMine provides a mock function for the type MockService
func (_mock *MockService) ListMine(ctx context.Context, userID uuid.UUID, status string) ([]View, error) {
	ret := _mock.Called(ctx, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for ListMine")
	}

	var r0 []View
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]View, error)); ok {
		return returnFunc(ctx, userID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []View); ok {
		r0 = returnFunc(ctx, userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]View)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListMine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMine'
type MockService_ListMine_Call struct {
	*mock.Call
}

// ListMine is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - status string
func (_e *MockService_Expecter) ListMine(ctx any, userID any, status any) *MockService_ListMine_Call {
	return &MockService_ListMine_Call{Call: _e.mock.On("ListMine", ctx, userID, status)}
}

func (_c *MockService_ListMine_Call) Run(run func(ctx context.Context, userID uuid.UUID, status string)) *MockService_ListMine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListMine_Call) Return(views []View, err error) *MockService_ListMine_Call {
	_c.Call.Return(views, err)
	return _c
}

func (_c *MockService_ListMine_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, status string) ([]View, error)) *MockService_ListMine_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID, c Choice) (Booking, error) {
	ret := _mock.Called(ctx, userID, bookingID, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, Choice) (Booking, error)); ok {
		return returnFunc(ctx, userID, bookingID, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, Choice) Booking); ok {
		r0 = returnFunc(ctx, userID, bookingID, c)
	} else {
		r0 = ret.Get(0).(Booking)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, Choice) error); ok {
		r1 = returnFunc(ctx, userID, bookingID, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - bookingID uuid.UUID
//   - c Choice
func (_e *MockService_Expecter) Update(ctx any, userID any, bookingID any, c any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, userID, bookingID, c)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID, c Choice)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 Choice
		if args[3] != nil {
			arg3 = args[3].(Choice)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(booking Booking, err error) *MockService_Update_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, bookingID uuid.UUID, c Choice) (Booking, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockRepository
func (_mock *MockRepository) Cancel(ctx context.Context, id uuid.UUID, now time.Time) error {
	ret := _mock.Called(ctx, id, now)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, id, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - now time.Time
func (_e *MockRepository_Expecter) Cancel(ctx any, id any, now any) *MockRepository_Cancel_Call {
	return &MockRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id, now)}
}

func (_c *MockRepository_Cancel_Call) Run(run func(ctx context.Context, id uuid.UUID, now time.Time)) *MockRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Cancel_Call) Return(err error) *MockRepository_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Cancel_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, now time.Time) error) *MockRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// ClosuresBetween provides a mock function for the type MockRepository
func (_mock *MockRepository) ClosuresBetween(ctx context.Context, restaurantID uuid.UUID, from time.Time, to time.Time) ([]Closure, error) {
	ret := _mock.Called(ctx, restaurantID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ClosuresBetween")
	}

	var r0 []Closure
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]Closure, error)); ok {
		return returnFunc(ctx, restaurantID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []Closure); ok {
		r0 = returnFunc(ctx, restaurantID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Closure)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, restaurantID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ClosuresBetween_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosuresBetween'
type MockRepository_ClosuresBetween_Call struct {
	*mock.Call
}

// ClosuresBetween is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) ClosuresBetween(ctx any, restaurantID any, from any, to any) *MockRepository_ClosuresBetween_Call {
	return &MockRepository_ClosuresBetween_Call{Call: _e.mock.On("ClosuresBetween", ctx, restaurantID, from, to)}
}

func (_c *MockRepository_ClosuresBetween_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, from time.Time, to time.Time)) *MockRepository_ClosuresBetween_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ClosuresBetween_Call) Return(closures []Closure, err error) *MockRepository_ClosuresBetween_Call {
	_c.Call.Return(closures, err)
	return _c
}

func (_c *MockRepository_ClosuresBetween_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, from time.Time, to time.Time) ([]Closure, error)) *MockRepository_ClosuresBetween_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, b *Booking) error {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Booking) error); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - b *Booking
func (_e *MockRepository_Expecter) Create(ctx any, b any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, b *Booking)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Booking
		if args[1] != nil {
			arg1 = args[1].(*Booking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, b *Booking) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (Booking, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) Booking); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Booking)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) FindByID(ctx any, id any) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(booking Booking, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (Booking, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOverlappingOwn provides a mock function for the type MockRepository
func (_mock *MockRepository) FindOverlappingOwn(ctx context.Context, restaurantID uuid.UUID, userID uuid.UUID, start time.Time, end time.Time, excludeID uuid.UUID) (*Booking, error) {
	ret := _mock.Called(ctx, restaurantID, userID, start, end, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for FindOverlappingOwn")
	}

	var r0 *Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time, uuid.UUID) (*Booking, error)); ok {
		return returnFunc(ctx, restaurantID, userID, start, end, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time, uuid.UUID) *Booking); ok {
		r0 = returnFunc(ctx, restaurantID, userID, start, end, excludeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID, userID, start, end, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindOverlappingOwn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOverlappingOwn'
type MockRepository_FindOverlappingOwn_Call struct {
	*mock.Call
}

// FindOverlappingOwn is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - userID uuid.UUID
//   - start time.Time
//   - end time.Time
//   - excludeID uuid.UUID
func (_e *MockRepository_Expecter) FindOverlappingOwn(ctx any, restaurantID any, userID any, start any, end any, excludeID any) *MockRepository_FindOverlappingOwn_Call {
	return &MockRepository_FindOverlappingOwn_Call{Call: _e.mock.On("FindOverlappingOwn", ctx, restaurantID, userID, start, end, excludeID)}
}

func (_c *MockRepository_FindOverlappingOwn_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, userID uuid.UUID, start time.Time, end time.Time, excludeID uuid.UUID)) *MockRepository_FindOverlappingOwn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 uuid.UUID
		if args[5] != nil {
			arg5 = args[5].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockRepository_FindOverlappingOwn_Call) Return(booking *Booking, err error) *MockRepository_FindOverlappingOwn_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockRepository_FindOverlappingOwn_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, userID uuid.UUID, start time.Time, end time.Time, excludeID uuid.UUID) (*Booking, error)) *MockRepository_FindOverlappingOwn_Call {
	_c.Call.Return(run)
	return _c
}

// FindRestaurant provides a mock function for the type MockRepository
func (_mock *MockRepository) FindRestaurant(ctx context.Context, id uuid.UUID, includeDeleted bool) (RestaurantInfo, error) {
	ret := _mock.Called(ctx, id, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for FindRestaurant")
	}

	var r0 RestaurantInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (RestaurantInfo, error)); ok {
		return returnFunc(ctx, id, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) RestaurantInfo); ok {
		r0 = returnFunc(ctx, id, includeDeleted)
	} else {
		r0 = ret.Get(0).(RestaurantInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, id, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindRestaurant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRestaurant'
type MockRepository_FindRestaurant_Call struct {
	*mock.Call
}

// FindRestaurant is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - includeDeleted bool
func (_e *MockRepository_Expecter) FindRestaurant(ctx any, id any, includeDeleted any) *MockRepository_FindRestaurant_Call {
	return &MockRepository_FindRestaurant_Call{Call: _e.mock.On("FindRestaurant", ctx, id, includeDeleted)}
}

func (_c *MockRepository_FindRestaurant_Call) Run(run func(ctx context.Context, id uuid.UUID, includeDeleted bool)) *MockRepository_FindRestaurant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FindRestaurant_Call) Return(restaurantInfo RestaurantInfo, err error) *MockRepository_FindRestaurant_Call {
	_c.Call.Return(restaurantInfo, err)
	return _c
}

func (_c *MockRepository_FindRestaurant_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, includeDeleted bool) (RestaurantInfo, error)) *MockRepository_FindRestaurant_Call {
	_c.Call.Return(run)
	return _c
}

// FindView provides a mock function for the type MockRepository
func (_mock *MockRepository) FindView(ctx context.Context, id uuid.UUID) (View, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindView")
	}

	var r0 View
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (View, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) View); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(View)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindView'
type MockRepository_FindView_Call struct {
	*mock.Call
}

// FindView is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) FindView(ctx any, id any) *MockRepository_FindView_Call {
	return &MockRepository_FindView_Call{Call: _e.mock.On("FindView", ctx, id)}
}

func (_c *MockRepository_FindView_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_FindView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindView_Call) Return(view View, err error) *MockRepository_FindView_Call {
	_c.Call.Return(view, err)
	return _c
}

func (_c *MockRepository_FindView_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (View, error)) *MockRepository_FindView_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockRepository
func (_mock *MockRepository) ListByUser(ctx context.Context, userID uuid.UUID, status string, now time.Time) ([]View, error) {
	ret := _mock.Called(ctx, userID, status, now)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []View
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) ([]View, error)); ok {
		return returnFunc(ctx, userID, status, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) []View); ok {
		r0 = returnFunc(ctx, userID, status, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]View)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, status, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - status string
//   - now time.Time
func (_e *MockRepository_Expecter) ListByUser(ctx any, userID any, status any, now any) *MockRepository_ListByUser_Call {
	return &MockRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, status, now)}
}

func (_c *MockRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, status string, now time.Time)) *MockRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ListByUser_Call) Return(views []View, err error) *MockRepository_ListByUser_Call {
	_c.Call.Return(views, err)
	return _c
}

func (_c *MockRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, status string, now time.Time) ([]View, error)) *MockRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListForRestaurant provides a mock function for the type MockRepository
func (_mock *MockRepository) ListForRestaurant(ctx context.Context, restaurantID uuid.UUID, from time.Time, to time.Time) ([]View, error) {
	ret := _mock.Called(ctx, restaurantID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListForRestaurant")
	}

	var r0 []View
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]View, error)); ok {
		return returnFunc(ctx, restaurantID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []View); ok {
		r0 = returnFunc(ctx, restaurantID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]View)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, restaurantID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListForRestaurant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForRestaurant'
type MockRepository_ListForRestaurant_Call struct {
	*mock.Call
}

// ListForRestaurant is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) ListForRestaurant(ctx any, restaurantID any, from any, to any) *MockRepository_ListForRestaurant_Call {
	return &MockRepository_ListForRestaurant_Call{Call: _e.mock.On("ListForRestaurant", ctx, restaurantID, from, to)}
}

func (_c *MockRepository_ListForRestaurant_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, from time.Time, to time.Time)) *MockRepository_ListForRestaurant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ListForRestaurant_Call) Return(views []View, err error) *MockRepository_ListForRestaurant_Call {
	_c.Call.Return(views, err)
	return _c
}

func (_c *MockRepository_ListForRestaurant_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, from time.Time, to time.Time) ([]View, error)) *MockRepository_ListForRestaurant_Call {
	_c.Call.Return(run)
	return _c
}

// LockByID provides a mock function for the type MockRepository
func (_mock *MockRepository) LockByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for LockByID")
	}

	var r0 Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (Booking, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) Booking); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Booking)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_LockByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockByID'
type MockRepository_LockByID_Call struct {
	*mock.Call
}

// LockByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) LockByID(ctx any, id any) *MockRepository_LockByID_Call {
	return &MockRepository_LockByID_Call{Call: _e.mock.On("LockByID", ctx, id)}
}

func (_c *MockRepository_LockByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_LockByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_LockByID_Call) Return(booking Booking, err error) *MockRepository_LockByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockRepository_LockByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (Booking, error)) *MockRepository_LockByID_Call {
	_c.Call.Return(run)
	return _c
}

// LockRestaurant provides a mock function for the type MockRepository
func (_mock *MockRepository) LockRestaurant(ctx context.Context, id uuid.UUID) (RestaurantInfo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for LockRestaurant")
	}

	var r0 RestaurantInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (RestaurantInfo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) RestaurantInfo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(RestaurantInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_LockRestaurant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockRestaurant'
type MockRepository_LockRestaurant_Call struct {
	*mock.Call
}

// LockRestaurant is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) LockRestaurant(ctx any, id any) *MockRepository_LockRestaurant_Call {
	return &MockRepository_LockRestaurant_Call{Call: _e.mock.On("LockRestaurant", ctx, id)}
}

func (_c *MockRepository_LockRestaurant_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_LockRestaurant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_LockRestaurant_Call) Return(restaurantInfo RestaurantInfo, err error) *MockRepository_LockRestaurant_Call {
	_c.Call.Return(restaurantInfo, err)
	return _c
}

func (_c *MockRepository_LockRestaurant_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (RestaurantInfo, error)) *MockRepository_LockRestaurant_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function for the type MockRepository
func (_mock *MockRepository) Notify(ctx context.Context, d notification.Draft) error {
	ret := _mock.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, notification.Draft) error); ok {
		r0 = returnFunc(ctx, d)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockRepository_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
//   - d notification.Draft
func (_e *MockRepository_Expecter) Notify(ctx any, d any) *MockRepository_Notify_Call {
	return &MockRepository_Notify_Call{Call: _e.mock.On("Notify", ctx, d)}
}

func (_c *MockRepository_Notify_Call) Run(run func(ctx context.Context, d notification.Draft)) *MockRepository_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 notification.Draft
		if args[1] != nil {
			arg1 = args[1].(notification.Draft)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Notify_Call) Return(err error) *MockRepository_Notify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Notify_Call) RunAndReturn(run func(ctx context.Context, d notification.Draft) error) *MockRepository_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// Overlapping provides a mock function for the type MockRepository
func (_mock *MockRepository) Overlapping(ctx context.Context, restaurantID uuid.UUID, start time.Time, end time.Time, excludeID uuid.UUID) ([]Booking, error) {
	ret := _mock.Called(ctx, restaurantID, start, end, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for Overlapping")
	}

	var r0 []Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, uuid.UUID) ([]Booking, error)); ok {
		return returnFunc(ctx, restaurantID, start, end, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, uuid.UUID) []Booking); ok {
		r0 = returnFunc(ctx, restaurantID, start, end, excludeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID, start, end, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Overlapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Overlapping'
type MockRepository_Overlapping_Call struct {
	*mock.Call
}

// Overlapping is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - start time.Time
//   - end time.Time
//   - excludeID uuid.UUID
func (_e *MockRepository_Expecter) Overlapping(ctx any, restaurantID any, start any, end any, excludeID any) *MockRepository_Overlapping_Call {
	return &MockRepository_Overlapping_Call{Call: _e.mock.On("Overlapping", ctx, restaurantID, start, end, excludeID)}
}

func (_c *MockRepository_Overlapping_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, start time.Time, end time.Time, excludeID uuid.UUID)) *MockRepository_Overlapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_Overlapping_Call) Return(bookings []Booking, err error) *MockRepository_Overlapping_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockRepository_Overlapping_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, start time.Time, end time.Time, excludeID uuid.UUID) ([]Booking, error)) *MockRepository_Overlapping_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function for the type MockRepository
func (_mock *MockRepository) Transaction(ctx context.Context, fn func(tx Repository) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx Repository) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx Repository) error
func (_e *MockRepository_Expecter) Transaction(ctx any, fn any) *MockRepository_Transaction_Call {
	return &MockRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(tx Repository) error)) *MockRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx Repository) error
		if args[1] != nil {
			arg1 = args[1].(func(tx Repository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Transaction_Call) Return(err error) *MockRepository_Transaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Transaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx Repository) error) error) *MockRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTime provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateTime(ctx context.Context, b *Booking) error {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTime")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Booking) error); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTime'
type MockRepository_UpdateTime_Call struct {
	*mock.Call
}

// UpdateTime is a helper method to define mock.On call
//   - ctx context.Context
//   - b *Booking
func (_e *MockRepository_Expecter) UpdateTime(ctx any, b any) *MockRepository_UpdateTime_Call {
	return &MockRepository_UpdateTime_Call{Call: _e.mock.On("UpdateTime", ctx, b)}
}

func (_c *MockRepository_UpdateTime_Call) Run(run func(ctx context.Context, b *Booking)) *MockRepository_UpdateTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Booking
		if args[1] != nil {
			arg1 = args[1].(*Booking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateTime_Call) Return(err error) *MockRepository_UpdateTime_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateTime_Call) RunAndReturn(run func(ctx context.Context, b *Booking) error) *MockRepository_UpdateTime_Call {
	_c.Call.Return(run)
	return _c
}
