// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Me provides a mock function for the type MockService
func (_mock *MockService) Me(ctx context.Context, id uuid.UUID) (Me, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 Me
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (Me, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) Me); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Me)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockService_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) Me(ctx any, id any) *MockService_Me_Call {
	return &MockService_Me_Call{Call: _e.mock.On("Me", ctx, id)}
}

func (_c *MockService_Me_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Me_Call) Return(me Me, err error) *MockService_Me_Call {
	_c.Call.Return(me, err)
	return _c
}

func (_c *MockService_Me_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (Me, error)) *MockService_Me_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) FindByID(ctx any, id any) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(user User, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (User, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByUID(ctx context.Context, uid string) (User, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for FindByUID")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (User, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) User); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUID'
type MockRepository_FindByUID_Call struct {
	*mock.Call
}

// FindByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockRepository_Expecter) FindByUID(ctx any, uid any) *MockRepository_FindByUID_Call {
	return &MockRepository_FindByUID_Call{Call: _e.mock.On("FindByUID", ctx, uid)}
}

func (_c *MockRepository_FindByUID_Call) Run(run func(ctx context.Context, uid string)) *MockRepository_FindByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByUID_Call) Return(user User, err error) *MockRepository_FindByUID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindByUID_Call) RunAndReturn(run func(ctx context.Context, uid string) (User, error)) *MockRepository_FindByUID_Call {
	_c.Call.Return(run)
	return _c
}

// OwnedRestaurants provides a mock function for the type MockRepository
func (_mock *MockRepository) OwnedRestaurants(ctx context.Context, userID uuid.UUID) ([]OwnedRestaurant, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for OwnedRestaurants")
	}

	var r0 []OwnedRestaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]OwnedRestaurant, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []OwnedRestaurant); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]OwnedRestaurant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_OwnedRestaurants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OwnedRestaurants'
type MockRepository_OwnedRestaurants_Call struct {
	*mock.Call
}

// OwnedRestaurants is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) OwnedRestaurants(ctx any, userID any) *MockRepository_OwnedRestaurants_Call {
	return &MockRepository_OwnedRestaurants_Call{Call: _e.mock.On("OwnedRestaurants", ctx, userID)}
}

func (_c *MockRepository_OwnedRestaurants_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRepository_OwnedRestaurants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_OwnedRestaurants_Call) Return(ownedRestaurants []OwnedRestaurant, err error) *MockRepository_OwnedRestaurants_Call {
	_c.Call.Return(ownedRestaurants, err)
	return _c
}

func (_c *MockRepository_OwnedRestaurants_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]OwnedRestaurant, error)) *MockRepository_OwnedRestaurants_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockRepository
func (_mock *MockRepository) Upsert(ctx context.Context, uid string, email string, displayName string) (User, error) {
	ret := _mock.Called(ctx, uid, email, displayName)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (User, error)); ok {
		return returnFunc(ctx, uid, email, displayName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) User); ok {
		r0 = returnFunc(ctx, uid, email, displayName)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, uid, email, displayName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - email string
//   - displayName string
func (_e *MockRepository_Expecter) Upsert(ctx any, uid any, email any, displayName any) *MockRepository_Upsert_Call {
	return &MockRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, uid, email, displayName)}
}

func (_c *MockRepository_Upsert_Call) Run(run func(ctx context.Context, uid string, email string, displayName string)) *MockRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Upsert_Call) Return(user User, err error) *MockRepository_Upsert_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, uid string, email string, displayName string) (User, error)) *MockRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
