// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middleware

import (
	"context"
	"jongyoung/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenVerifier creates a new instance of MockTokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenVerifier {
	mock := &MockTokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenVerifier is an autogenerated mock type for the TokenVerifier type
type MockTokenVerifier struct {
	mock.Mock
}

type MockTokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenVerifier) EXPECT() *MockTokenVerifier_Expecter {
	return &MockTokenVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockTokenVerifier
func (_mock *MockTokenVerifier) Verify(ctx context.Context, rawToken string) (Claims, error) {
	ret := _mock.Called(ctx, rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Claims, error)); ok {
		return returnFunc(ctx, rawToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Claims); ok {
		r0 = returnFunc(ctx, rawToken)
	} else {
		r0 = ret.Get(0).(Claims)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockTokenVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - rawToken string
func (_e *MockTokenVerifier_Expecter) Verify(ctx any, rawToken any) *MockTokenVerifier_Verify_Call {
	return &MockTokenVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, rawToken)}
}

func (_c *MockTokenVerifier_Verify_Call) Run(run func(ctx context.Context, rawToken string)) *MockTokenVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenVerifier_Verify_Call) Return(claims Claims, err error) *MockTokenVerifier_Verify_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockTokenVerifier_Verify_Call) RunAndReturn(run func(ctx context.Context, rawToken string) (Claims, error)) *MockTokenVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvisioner creates a new instance of MockUserProvisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvisioner {
	mock := &MockUserProvisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserProvisioner is an autogenerated mock type for the UserProvisioner type
type MockUserProvisioner struct {
	mock.Mock
}

type MockUserProvisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvisioner) EXPECT() *MockUserProvisioner_Expecter {
	return &MockUserProvisioner_Expecter{mock: &_m.Mock}
}

// EnsureExists provides a mock function for the type MockUserProvisioner
func (_mock *MockUserProvisioner) EnsureExists(ctx context.Context, uid string, email string, displayName string) (user.User, error) {
	ret := _mock.Called(ctx, uid, email, displayName)

	if len(ret) == 0 {
		panic("no return value specified for EnsureExists")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (user.User, error)); ok {
		return returnFunc(ctx, uid, email, displayName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) user.User); ok {
		r0 = returnFunc(ctx, uid, email, displayName)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, uid, email, displayName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvisioner_EnsureExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureExists'
type MockUserProvisioner_EnsureExists_Call struct {
	*mock.Call
}

// EnsureExists is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - email string
//   - displayName string
func (_e *MockUserProvisioner_Expecter) EnsureExists(ctx any, uid any, email any, displayName any) *MockUserProvisioner_EnsureExists_Call {
	return &MockUserProvisioner_EnsureExists_Call{Call: _e.mock.On("EnsureExists", ctx, uid, email, displayName)}
}

func (_c *MockUserProvisioner_EnsureExists_Call) Run(run func(ctx context.Context, uid string, email string, displayName string)) *MockUserProvisioner_EnsureExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserProvisioner_EnsureExists_Call) Return(user1 user.User, err error) *MockUserProvisioner_EnsureExists_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserProvisioner_EnsureExists_Call) RunAndReturn(run func(ctx context.Context, uid string, email string, displayName string) (user.User, error)) *MockUserProvisioner_EnsureExists_Call {
	_c.Call.Return(run)
	return _c
}
