// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package restaurant

import (
	"context"
	"jongyoung/internal/booking"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddImage provides a mock function for the type MockService
func (_mock *MockService) AddImage(ctx context.Context, userID uuid.UUID, id uuid.UUID, url string) (Image, error) {
	ret := _mock.Called(ctx, userID, id, url)

	if len(ret) == 0 {
		panic("no return value specified for AddImage")
	}

	var r0 Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (Image, error)); ok {
		return returnFunc(ctx, userID, id, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) Image); ok {
		r0 = returnFunc(ctx, userID, id, url)
	} else {
		r0 = ret.Get(0).(Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, id, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_AddImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddImage'
type MockService_AddImage_Call struct {
	*mock.Call
}

// AddImage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - url string
func (_e *MockService_Expecter) AddImage(ctx any, userID any, id any, url any) *MockService_AddImage_Call {
	return &MockService_AddImage_Call{Call: _e.mock.On("AddImage", ctx, userID, id, url)}
}

func (_c *MockService_AddImage_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, url string)) *MockService_AddImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_AddImage_Call) Return(image Image, err error) *MockService_AddImage_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockService_AddImage_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, url string) (Image, error)) *MockService_AddImage_Call {
	_c.Call.Return(run)
	return _c
}

// Availability provides a mock function for the type MockService
func (_mock *MockService) Availability(ctx context.Context, id uuid.UUID, date time.Time) (Restaurant, []booking.Slot, error) {
	ret := _mock.Called(ctx, id, date)

	if len(ret) == 0 {
		panic("no return value specified for Availability")
	}

	var r0 Restaurant
	var r1 []booking.Slot
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (Restaurant, []booking.Slot, error)); ok {
		return returnFunc(ctx, id, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) Restaurant); ok {
		r0 = returnFunc(ctx, id, date)
	} else {
		r0 = ret.Get(0).(Restaurant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) []booking.Slot); ok {
		r1 = returnFunc(ctx, id, date)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]booking.Slot)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r2 = returnFunc(ctx, id, date)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_Availability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Availability'
type MockService_Availability_Call struct {
	*mock.Call
}

// Availability is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - date time.Time
func (_e *MockService_Expecter) Availability(ctx any, id any, date any) *MockService_Availability_Call {
	return &MockService_Availability_Call{Call: _e.mock.On("Availability", ctx, id, date)}
}

func (_c *MockService_Availability_Call) Run(run func(ctx context.Context, id uuid.UUID, date time.Time)) *MockService_Availability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Availability_Call) Return(restaurant Restaurant, slots []booking.Slot, err error) *MockService_Availability_Call {
	_c.Call.Return(restaurant, slots, err)
	return _c
}

func (_c *MockService_Availability_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, date time.Time) (Restaurant, []booking.Slot, error)) *MockService_Availability_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, ownerID uuid.UUID, in Input, imageURLs []string) (Restaurant, error) {
	ret := _mock.Called(ctx, ownerID, in, imageURLs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 Restaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, Input, []string) (Restaurant, error)); ok {
		return returnFunc(ctx, ownerID, in, imageURLs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, Input, []string) Restaurant); ok {
		r0 = returnFunc(ctx, ownerID, in, imageURLs)
	} else {
		r0 = ret.Get(0).(Restaurant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, Input, []string) error); ok {
		r1 = returnFunc(ctx, ownerID, in, imageURLs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uuid.UUID
//   - in Input
//   - imageURLs []string
func (_e *MockService_Expecter) Create(ctx any, ownerID any, in any, imageURLs any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, ownerID, in, imageURLs)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, ownerID uuid.UUID, in Input, imageURLs []string)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 Input
		if args[2] != nil {
			arg2 = args[2].(Input)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(restaurant Restaurant, err error) *MockService_Create_Call {
	_c.Call.Return(restaurant, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, ownerID uuid.UUID, in Input, imageURLs []string) (Restaurant, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockService_Expecter) Delete(ctx any, userID any, id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImage provides a mock function for the type MockService
func (_mock *MockService) DeleteImage(ctx context.Context, userID uuid.UUID, id uuid.UUID, imageID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id, imageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImage'
type MockService_DeleteImage_Call struct {
	*mock.Call
}

// DeleteImage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - imageID uuid.UUID
func (_e *MockService_Expecter) DeleteImage(ctx any, userID any, id any, imageID any) *MockService_DeleteImage_Call {
	return &MockService_DeleteImage_Call{Call: _e.mock.On("DeleteImage", ctx, userID, id, imageID)}
}

func (_c *MockService_DeleteImage_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, imageID uuid.UUID)) *MockService_DeleteImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_DeleteImage_Call) Return(err error) *MockService_DeleteImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteImage_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, imageID uuid.UUID) error) *MockService_DeleteImage_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, id uuid.UUID) (Restaurant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 Restaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (Restaurant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) Restaurant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Restaurant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) Get(ctx any, id any) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(restaurant Restaurant, err error) *MockService_Get_Call {
	_c.Call.Return(restaurant, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (Restaurant, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, q ListQuery) ([]ListItem, int64, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []ListItem
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListQuery) ([]ListItem, int64, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListQuery) []ListItem); ok {
		r0 = returnFunc(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ListItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ListQuery) int64); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, ListQuery) error); ok {
		r2 = returnFunc(ctx, q)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - q ListQuery
func (_e *MockService_Expecter) List(ctx any, q any) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, q)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, q ListQuery)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ListQuery
		if args[1] != nil {
			arg1 = args[1].(ListQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(listItems []ListItem, n int64, err error) *MockService_List_Call {
	_c.Call.Return(listItems, n, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, q ListQuery) ([]ListItem, int64, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NextAvailable provides a mock function for the type MockService
func (_mock *MockService) NextAvailable(ctx context.Context, id uuid.UUID, date time.Time, minute int, party int) (*NextAvailable, error) {
	ret := _mock.Called(ctx, id, date, minute, party)

	if len(ret) == 0 {
		panic("no return value specified for NextAvailable")
	}

	var r0 *NextAvailable
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) (*NextAvailable, error)); ok {
		return returnFunc(ctx, id, date, minute, party)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, int, int) *NextAvailable); ok {
		r0 = returnFunc(ctx, id, date, minute, party)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NextAvailable)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, id, date, minute, party)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NextAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextAvailable'
type MockService_NextAvailable_Call struct {
	*mock.Call
}

// NextAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - date time.Time
//   - minute int
//   - party int
func (_e *MockService_Expecter) NextAvailable(ctx any, id any, date any, minute any, party any) *MockService_NextAvailable_Call {
	return &MockService_NextAvailable_Call{Call: _e.mock.On("NextAvailable", ctx, id, date, minute, party)}
}

func (_c *MockService_NextAvailable_Call) Run(run func(ctx context.Context, id uuid.UUID, date time.Time, minute int, party int)) *MockService_NextAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_NextAvailable_Call) Return(nextAvailable *NextAvailable, err error) *MockService_NextAvailable_Call {
	_c.Call.Return(nextAvailable, err)
	return _c
}

func (_c *MockService_NextAvailable_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, date time.Time, minute int, party int) (*NextAvailable, error)) *MockService_NextAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, userID uuid.UUID, id uuid.UUID, in Input) (Restaurant, error) {
	ret := _mock.Called(ctx, userID, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 Restaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, Input) (Restaurant, error)); ok {
		return returnFunc(ctx, userID, id, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, Input) Restaurant); ok {
		r0 = returnFunc(ctx, userID, id, in)
	} else {
		r0 = ret.Get(0).(Restaurant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, Input) error); ok {
		r1 = returnFunc(ctx, userID, id, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - in Input
func (_e *MockService_Expecter) Update(ctx any, userID any, id any, in any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, userID, id, in)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, in Input)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 Input
		if args[3] != nil {
			arg3 = args[3].(Input)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(restaurant Restaurant, err error) *MockService_Update_Call {
	_c.Call.Return(restaurant, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, in Input) (Restaurant, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddImage provides a mock function for the type MockRepository
func (_mock *MockRepository) AddImage(ctx context.Context, img *Image) error {
	ret := _mock.Called(ctx, img)

	if len(ret) == 0 {
		panic("no return value specified for AddImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Image) error); ok {
		r0 = returnFunc(ctx, img)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddImage'
type MockRepository_AddImage_Call struct {
	*mock.Call
}

// AddImage is a helper method to define mock.On call
//   - ctx context.Context
//   - img *Image
func (_e *MockRepository_Expecter) AddImage(ctx any, img any) *MockRepository_AddImage_Call {
	return &MockRepository_AddImage_Call{Call: _e.mock.On("AddImage", ctx, img)}
}

func (_c *MockRepository_AddImage_Call) Run(run func(ctx context.Context, img *Image)) *MockRepository_AddImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Image
		if args[1] != nil {
			arg1 = args[1].(*Image)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_AddImage_Call) Return(err error) *MockRepository_AddImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddImage_Call) RunAndReturn(run func(ctx context.Context, img *Image) error) *MockRepository_AddImage_Call {
	_c.Call.Return(run)
	return _c
}

// BookingsBetween provides a mock function for the type MockRepository
func (_mock *MockRepository) BookingsBetween(ctx context.Context, restaurantIDs []uuid.UUID, from time.Time, to time.Time) ([]booking.Booking, error) {
	ret := _mock.Called(ctx, restaurantIDs, from, to)

	if len(ret) == 0 {
		panic("no return value specified for BookingsBetween")
	}

	var r0 []booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, time.Time, time.Time) ([]booking.Booking, error)); ok {
		return returnFunc(ctx, restaurantIDs, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, time.Time, time.Time) []booking.Booking); ok {
		r0 = returnFunc(ctx, restaurantIDs, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, restaurantIDs, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_BookingsBetween_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BookingsBetween'
type MockRepository_BookingsBetween_Call struct {
	*mock.Call
}

// BookingsBetween is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantIDs []uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepository_Expecter) BookingsBetween(ctx any, restaurantIDs any, from any, to any) *MockRepository_BookingsBetween_Call {
	return &MockRepository_BookingsBetween_Call{Call: _e.mock.On("BookingsBetween", ctx, restaurantIDs, from, to)}
}

func (_c *MockRepository_BookingsBetween_Call) Run(run func(ctx context.Context, restaurantIDs []uuid.UUID, from time.Time, to time.Time)) *MockRepository_BookingsBetween_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_BookingsBetween_Call) Return(bookings []booking.Booking, err error) *MockRepository_BookingsBetween_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockRepository_BookingsBetween_Call) RunAndReturn(run func(ctx context.Context, restaurantIDs []uuid.UUID, from time.Time, to time.Time) ([]booking.Booking, error)) *MockRepository_BookingsBetween_Call {
	_c.Call.Return(run)
	return _c
}

// CancelFutureBookings provides a mock function for the type MockRepository
func (_mock *MockRepository) CancelFutureBookings(ctx context.Context, restaurantID uuid.UUID, now time.Time) (int64, error) {
	ret := _mock.Called(ctx, restaurantID, now)

	if len(ret) == 0 {
		panic("no return value specified for CancelFutureBookings")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (int64, error)); ok {
		return returnFunc(ctx, restaurantID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) int64); ok {
		r0 = returnFunc(ctx, restaurantID, now)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, restaurantID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CancelFutureBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelFutureBookings'
type MockRepository_CancelFutureBookings_Call struct {
	*mock.Call
}

// CancelFutureBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - now time.Time
func (_e *MockRepository_Expecter) CancelFutureBookings(ctx any, restaurantID any, now any) *MockRepository_CancelFutureBookings_Call {
	return &MockRepository_CancelFutureBookings_Call{Call: _e.mock.On("CancelFutureBookings", ctx, restaurantID, now)}
}

func (_c *MockRepository_CancelFutureBookings_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, now time.Time)) *MockRepository_CancelFutureBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CancelFutureBookings_Call) Return(n int64, err error) *MockRepository_CancelFutureBookings_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CancelFutureBookings_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, now time.Time) (int64, error)) *MockRepository_CancelFutureBookings_Call {
	_c.Call.Return(run)
	return _c
}

// CountImages provides a mock function for the type MockRepository
func (_mock *MockRepository) CountImages(ctx context.Context, restaurantID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for CountImages")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, restaurantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, restaurantID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CountImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountImages'
type MockRepository_CountImages_Call struct {
	*mock.Call
}

// CountImages is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
func (_e *MockRepository_Expecter) CountImages(ctx any, restaurantID any) *MockRepository_CountImages_Call {
	return &MockRepository_CountImages_Call{Call: _e.mock.On("CountImages", ctx, restaurantID)}
}

func (_c *MockRepository_CountImages_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID)) *MockRepository_CountImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CountImages_Call) Return(n int64, err error) *MockRepository_CountImages_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CountImages_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID) (int64, error)) *MockRepository_CountImages_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, rest *Restaurant) error {
	ret := _mock.Called(ctx, rest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Restaurant) error); ok {
		r0 = returnFunc(ctx, rest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rest *Restaurant
func (_e *MockRepository_Expecter) Create(ctx any, rest any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, rest)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, rest *Restaurant)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Restaurant
		if args[1] != nil {
			arg1 = args[1].(*Restaurant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, rest *Restaurant) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImage provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteImage(ctx context.Context, restaurantID uuid.UUID, imageID uuid.UUID) error {
	ret := _mock.Called(ctx, restaurantID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, restaurantID, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImage'
type MockRepository_DeleteImage_Call struct {
	*mock.Call
}

// DeleteImage is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - imageID uuid.UUID
func (_e *MockRepository_Expecter) DeleteImage(ctx any, restaurantID any, imageID any) *MockRepository_DeleteImage_Call {
	return &MockRepository_DeleteImage_Call{Call: _e.mock.On("DeleteImage", ctx, restaurantID, imageID)}
}

func (_c *MockRepository_DeleteImage_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, imageID uuid.UUID)) *MockRepository_DeleteImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteImage_Call) Return(err error) *MockRepository_DeleteImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteImage_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, imageID uuid.UUID) error) *MockRepository_DeleteImage_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (Restaurant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 Restaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (Restaurant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) Restaurant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Restaurant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) FindByID(ctx any, id any) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(restaurant Restaurant, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(restaurant, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (Restaurant, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FutureBookings provides a mock function for the type MockRepository
func (_mock *MockRepository) FutureBookings(ctx context.Context, restaurantID uuid.UUID, now time.Time) ([]booking.Booking, error) {
	ret := _mock.Called(ctx, restaurantID, now)

	if len(ret) == 0 {
		panic("no return value specified for FutureBookings")
	}

	var r0 []booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) ([]booking.Booking, error)); ok {
		return returnFunc(ctx, restaurantID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) []booking.Booking); ok {
		r0 = returnFunc(ctx, restaurantID, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, restaurantID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FutureBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FutureBookings'
type MockRepository_FutureBookings_Call struct {
	*mock.Call
}

// FutureBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - now time.Time
func (_e *MockRepository_Expecter) FutureBookings(ctx any, restaurantID any, now any) *MockRepository_FutureBookings_Call {
	return &MockRepository_FutureBookings_Call{Call: _e.mock.On("FutureBookings", ctx, restaurantID, now)}
}

func (_c *MockRepository_FutureBookings_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, now time.Time)) *MockRepository_FutureBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FutureBookings_Call) Return(bookings []booking.Booking, err error) *MockRepository_FutureBookings_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockRepository_FutureBookings_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, now time.Time) ([]booking.Booking, error)) *MockRepository_FutureBookings_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, q ListQuery) ([]Restaurant, int64, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []Restaurant
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListQuery) ([]Restaurant, int64, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListQuery) []Restaurant); ok {
		r0 = returnFunc(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Restaurant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ListQuery) int64); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, ListQuery) error); ok {
		r2 = returnFunc(ctx, q)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - q ListQuery
func (_e *MockRepository_Expecter) List(ctx any, q any) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, q)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, q ListQuery)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ListQuery
		if args[1] != nil {
			arg1 = args[1].(ListQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(restaurants []Restaurant, n int64, err error) *MockRepository_List_Call {
	_c.Call.Return(restaurants, n, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, q ListQuery) ([]Restaurant, int64, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// LockByID provides a mock function for the type MockRepository
func (_mock *MockRepository) LockByID(ctx context.Context, id uuid.UUID) (Restaurant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for LockByID")
	}

	var r0 Restaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (Restaurant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) Restaurant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Restaurant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_LockByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockByID'
type MockRepository_LockByID_Call struct {
	*mock.Call
}

// LockByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) LockByID(ctx any, id any) *MockRepository_LockByID_Call {
	return &MockRepository_LockByID_Call{Call: _e.mock.On("LockByID", ctx, id)}
}

func (_c *MockRepository_LockByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_LockByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_LockByID_Call) Return(restaurant Restaurant, err error) *MockRepository_LockByID_Call {
	_c.Call.Return(restaurant, err)
	return _c
}

func (_c *MockRepository_LockByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (Restaurant, error)) *MockRepository_LockByID_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockRepository
func (_mock *MockRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) SoftDelete(ctx any, id any) *MockRepository_SoftDelete_Call {
	return &MockRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SoftDelete_Call) Return(err error) *MockRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function for the type MockRepository
func (_mock *MockRepository) Transaction(ctx context.Context, fn func(tx Repository) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx Repository) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx Repository) error
func (_e *MockRepository_Expecter) Transaction(ctx any, fn any) *MockRepository_Transaction_Call {
	return &MockRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(tx Repository) error)) *MockRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx Repository) error
		if args[1] != nil {
			arg1 = args[1].(func(tx Repository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Transaction_Call) Return(err error) *MockRepository_Transaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Transaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx Repository) error) error) *MockRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, rest *Restaurant) error {
	ret := _mock.Called(ctx, rest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Restaurant) error); ok {
		r0 = returnFunc(ctx, rest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rest *Restaurant
func (_e *MockRepository_Expecter) Update(ctx any, rest any) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, rest)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, rest *Restaurant)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Restaurant
		if args[1] != nil {
			arg1 = args[1].(*Restaurant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(err error) *MockRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, rest *Restaurant) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
