// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package review

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, score int, body string) (Review, error) {
	ret := _mock.Called(ctx, userID, restaurantID, score, body)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string) (Review, error)); ok {
		return returnFunc(ctx, userID, restaurantID, score, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string) Review); ok {
		r0 = returnFunc(ctx, userID, restaurantID, score, body)
	} else {
		r0 = ret.Get(0).(Review)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, string) error); ok {
		r1 = returnFunc(ctx, userID, restaurantID, score, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - restaurantID uuid.UUID
//   - score int
//   - body string
func (_e *MockService_Expecter) Create(ctx any, userID any, restaurantID any, score any, body any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, userID, restaurantID, score, body)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, score int, body string)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(review Review, err error) *MockService_Create_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, score int, body string) (Review, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, restaurantID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - restaurantID uuid.UUID
func (_e *MockService_Expecter) Delete(ctx any, userID any, restaurantID any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, restaurantID)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, restaurantID uuid.UUID, limit int, offset int) ([]View, int64, error) {
	ret := _mock.Called(ctx, restaurantID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []View
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]View, int64, error)); ok {
		return returnFunc(ctx, restaurantID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []View); ok {
		r0 = returnFunc(ctx, restaurantID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]View)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int64); ok {
		r1 = returnFunc(ctx, restaurantID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, restaurantID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) List(ctx any, restaurantID any, limit any, offset any) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, restaurantID, limit, offset)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, limit int, offset int)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(views []View, n int64, err error) *MockService_List_Call {
	_c.Call.Return(views, n, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, limit int, offset int) ([]View, int64, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Mine provides a mock function for the type MockService
func (_mock *MockService) Mine(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID) (Review, error) {
	ret := _mock.Called(ctx, userID, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for Mine")
	}

	var r0 Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (Review, error)); ok {
		return returnFunc(ctx, userID, restaurantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) Review); ok {
		r0 = returnFunc(ctx, userID, restaurantID)
	} else {
		r0 = ret.Get(0).(Review)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, restaurantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Mine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mine'
type MockService_Mine_Call struct {
	*mock.Call
}

// Mine is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - restaurantID uuid.UUID
func (_e *MockService_Expecter) Mine(ctx any, userID any, restaurantID any) *MockService_Mine_Call {
	return &MockService_Mine_Call{Call: _e.mock.On("Mine", ctx, userID, restaurantID)}
}

func (_c *MockService_Mine_Call) Run(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID)) *MockService_Mine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Mine_Call) Return(review Review, err error) *MockService_Mine_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockService_Mine_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID) (Review, error)) *MockService_Mine_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, score int, body string) (Review, error) {
	ret := _mock.Called(ctx, userID, restaurantID, score, body)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string) (Review, error)); ok {
		return returnFunc(ctx, userID, restaurantID, score, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string) Review); ok {
		r0 = returnFunc(ctx, userID, restaurantID, score, body)
	} else {
		r0 = ret.Get(0).(Review)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, string) error); ok {
		r1 = returnFunc(ctx, userID, restaurantID, score, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - restaurantID uuid.UUID
//   - score int
//   - body string
func (_e *MockService_Expecter) Update(ctx any, userID any, restaurantID any, score any, body any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, userID, restaurantID, score, body)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, score int, body string)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(review Review, err error) *MockService_Update_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, restaurantID uuid.UUID, score int, body string) (Review, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AdjustRating provides a mock function for the type MockRepository
func (_mock *MockRepository) AdjustRating(ctx context.Context, restaurantID uuid.UUID, sumDelta int, countDelta int) error {
	ret := _mock.Called(ctx, restaurantID, sumDelta, countDelta)

	if len(ret) == 0 {
		panic("no return value specified for AdjustRating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) error); ok {
		r0 = returnFunc(ctx, restaurantID, sumDelta, countDelta)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AdjustRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustRating'
type MockRepository_AdjustRating_Call struct {
	*mock.Call
}

// AdjustRating is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - sumDelta int
//   - countDelta int
func (_e *MockRepository_Expecter) AdjustRating(ctx any, restaurantID any, sumDelta any, countDelta any) *MockRepository_AdjustRating_Call {
	return &MockRepository_AdjustRating_Call{Call: _e.mock.On("AdjustRating", ctx, restaurantID, sumDelta, countDelta)}
}

func (_c *MockRepository_AdjustRating_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, sumDelta int, countDelta int)) *MockRepository_AdjustRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_AdjustRating_Call) Return(err error) *MockRepository_AdjustRating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AdjustRating_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, sumDelta int, countDelta int) error) *MockRepository_AdjustRating_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, rv *Review) error {
	ret := _mock.Called(ctx, rv)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Review) error); ok {
		r0 = returnFunc(ctx, rv)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rv *Review
func (_e *MockRepository_Expecter) Create(ctx any, rv any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, rv)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, rv *Review)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Review
		if args[1] != nil {
			arg1 = args[1].(*Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, rv *Review) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Delete(ctx any, id any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindOwn provides a mock function for the type MockRepository
func (_mock *MockRepository) FindOwn(ctx context.Context, restaurantID uuid.UUID, userID uuid.UUID) (Review, error) {
	ret := _mock.Called(ctx, restaurantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindOwn")
	}

	var r0 Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (Review, error)); ok {
		return returnFunc(ctx, restaurantID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) Review); ok {
		r0 = returnFunc(ctx, restaurantID, userID)
	} else {
		r0 = ret.Get(0).(Review)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindOwn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOwn'
type MockRepository_FindOwn_Call struct {
	*mock.Call
}

// FindOwn is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) FindOwn(ctx any, restaurantID any, userID any) *MockRepository_FindOwn_Call {
	return &MockRepository_FindOwn_Call{Call: _e.mock.On("FindOwn", ctx, restaurantID, userID)}
}

func (_c *MockRepository_FindOwn_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, userID uuid.UUID)) *MockRepository_FindOwn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FindOwn_Call) Return(review Review, err error) *MockRepository_FindOwn_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockRepository_FindOwn_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, userID uuid.UUID) (Review, error)) *MockRepository_FindOwn_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, restaurantID uuid.UUID, limit int, offset int) ([]View, int64, error) {
	ret := _mock.Called(ctx, restaurantID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []View
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]View, int64, error)); ok {
		return returnFunc(ctx, restaurantID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []View); ok {
		r0 = returnFunc(ctx, restaurantID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]View)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int64); ok {
		r1 = returnFunc(ctx, restaurantID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, restaurantID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) List(ctx any, restaurantID any, limit any, offset any) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, restaurantID, limit, offset)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, limit int, offset int)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(views []View, n int64, err error) *MockRepository_List_Call {
	_c.Call.Return(views, n, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, limit int, offset int) ([]View, int64, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// RestaurantOwner provides a mock function for the type MockRepository
func (_mock *MockRepository) RestaurantOwner(ctx context.Context, restaurantID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for RestaurantOwner")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, restaurantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_RestaurantOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestaurantOwner'
type MockRepository_RestaurantOwner_Call struct {
	*mock.Call
}

// RestaurantOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
func (_e *MockRepository_Expecter) RestaurantOwner(ctx any, restaurantID any) *MockRepository_RestaurantOwner_Call {
	return &MockRepository_RestaurantOwner_Call{Call: _e.mock.On("RestaurantOwner", ctx, restaurantID)}
}

func (_c *MockRepository_RestaurantOwner_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID)) *MockRepository_RestaurantOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RestaurantOwner_Call) Return(uUID uuid.UUID, err error) *MockRepository_RestaurantOwner_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRepository_RestaurantOwner_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID) (uuid.UUID, error)) *MockRepository_RestaurantOwner_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function for the type MockRepository
func (_mock *MockRepository) Transaction(ctx context.Context, fn func(tx Repository) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx Repository) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx Repository) error
func (_e *MockRepository_Expecter) Transaction(ctx any, fn any) *MockRepository_Transaction_Call {
	return &MockRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(tx Repository) error)) *MockRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx Repository) error
		if args[1] != nil {
			arg1 = args[1].(func(tx Repository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Transaction_Call) Return(err error) *MockRepository_Transaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Transaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx Repository) error) error) *MockRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, rv *Review) error {
	ret := _mock.Called(ctx, rv)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Review) error); ok {
		r0 = returnFunc(ctx, rv)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rv *Review
func (_e *MockRepository_Expecter) Update(ctx any, rv any) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, rv)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, rv *Review)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Review
		if args[1] != nil {
			arg1 = args[1].(*Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(err error) *MockRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, rv *Review) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
